CREATE DATABASE IF NOT EXISTS c8gd2s CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE c8gd2s;

CREATE TABLE company_types(
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(150) NOT NULL UNIQUE,
    description VARCHAR(100) DEFAULT NULL
);

CREATE TABLE industries(
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(150) NOT NULL UNIQUE,
    description VARCHAR(100) DEFAULT NULL
);

CREATE TABLE organization_types(
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(150) NOT NULL UNIQUE,
    description VARCHAR(100) DEFAULT NULL
);

CREATE TABLE sectors(
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(150) NOT NULL UNIQUE,
    description VARCHAR(100) DEFAULT NULL
);

INSERT INTO company_types(name)
VALUES
("Private "),
("Public"),
("Limited Partnership"),
("General Partnership"),
("Chartered Company"),
("Statutory Corporation"),
("State-Owned"),
("Holding"),
("Subsidiary"),
("Charitable Incorporated Organisation (UK)"),
("Reciprocal Inter-Insurance Exchange");





INSERT INTO organization_types(name)
VALUES
("Sole proprietorship"),
("Corporation"),
("Limited liability company"),
("Partnership"),
("Joint Venture"),
("Nonprofit"),
("Cooperative");
-- ("Functional"),
-- ("Divisional"),
-- ("Matrix");


INSERT INTO sectors(name)
VALUES
("5G, IoT & Edge Computing"),
("Advanced Media & Technology"),
("Aerospace & Defense"),
("Agriculture & Forestry"),
("Agrochemicals"),
("Art law"),
("Artificial Intelligence"),
("Asset Management"),
("Automotive"),
("Autonomous Things"),
("Blockchain"),
("Business & Consumer Services"),
("Cannabis"),
("Cell and gene therapy"),
("Chemicals"),
("Communications"),
("Construction"),
("Consumer"),
("Coronavirus & Data Protection"),
("Corporate Lending"),
("Cyber"),
("Digital Health"),
("Digital Workforces"),
("Education"),
("Emerging Technologies"),
("Energy & Natural Resources"),
("Environment"),
("Extended Reality"),
("Fashion & Beauty"),
("Financial Market Infrastructure"),
("Financial Services"),
("Fintech"),
("Food & Beverage"),
("Government"),
("Haulage"),
("Healthcare"),
("Hotels & Leisure"),
("Industrial Goods & Machinery"),
("Information & Communication Technologies"),
("Information Security"),
("Innovation"),
("Internet of things (IoT)"),
("Investment Banking"),
("Life Sciences"),
("Manufacturing"),
("Maritime"),
("Media"),
("Medical Devices"),
("Mining & Metals"),
("Oil & Gas"),
("Packaging"),
("Pharmaceuticals & Biotechnology"),
("Power"),
("Private Banking"),
("Rail"),
("Real Estate"),
("Renewables & Sustainability"),
("Retail & Wholesale"),
("Sport"),
("Sustainability"),
("Technology, Media & Telecom"),
("Transport, Logistics"),
("Travel & Tourism");



INSERT INTO industries(name)
VALUES ("Abortion Policy/Anti-Abortion"),
("Abortion Policy/Pro-Abortion Rights"),
("Accountants"),
("Advertising/Public Relations"),
("Aerospace, Defense Contractors"),
("Agribusiness"),
("Agricultural Services & Products"),
("Agriculture"),
("Air Transport"),
("Air Transport Unions"),
("Airlines"),
("Alcoholic Beverages"),
("Alternative Energy Production & Services"),
("Architectural Services"),
("Attorneys/Law Firms"),
("Auto Dealers"),
("Auto Dealers, Japanese"),
("Auto Manufacturers"),
("Automotive"),
("Banking, Mortgage"),
("Banks, Commercial"),
("Banks, Savings & Loans"),
("Bars & Restaurants"),
("Beer, Wine & Liquor"),
("Books, Magazines & Newspapers"),
("Broadcasters, Radio/TV"),
("Builders/General Contractors"),
("Builders/Residential"),
("Building Materials & Equipment"),
("Building Trade Unions"),
("Business Associations"),
("Business Services"),
("Cable & Satellite TV Production & Distribution"),
("Candidate Committees"),
("Candidate Committees, Democratic"),
("Candidate Committees, Republican"),
("Car Dealers"),
("Car Dealers, Imports"),
("Car Manufacturers"),
("Casinos / Gambling"),
("Cattle Ranchers/Livestock"),
("Chemical & Related Manufacturing"),
("Chiropractors"),
("Civil Servants/Public Officials"),
("Clergy & Religious Organizations"),
("Clothing Manufacturing"),
("Coal Mining"),
("Colleges, Universities & Schools"),
("Commercial Banks"),
("Commercial TV & Radio Stations"),
("Communications/Electronics"),
("Computer Software"),
("Conservative/Republican"),
("Construction"),
("Construction Services"),
("Construction Unions"),
("Credit Unions"),
("Computer"),
("Crop Production & Basic Processing"),
("Cruise Lines"),
("Cruise Ships & Lines"),
("Dairy"),
("Defense"),
("Defense Aerospace"),
("Defense Electronics"),
("Defense/Foreign Policy Advocates"),
("Democratic Candidate Committees"),
("Democratic Leadership PACs"),
("Democratic/Liberal"),
("Dentists"),
("Doctors & Other Health Professionals"),
("Drug Manufacturers"),
("Education"),
("Electric Utilities"),
("Electronics Manufacturing & Equipment"),
("Electronics, Defense Contractors"),
("Energy"),
("Energy & Natural Resources"),
("Engineering"),
("Entertainment Industry"),
("Environment"),
("Farm Bureaus"),
("Farming"),
("Fashion"),
("Film"),
("Finance / Credit Companies"),
("Finance, Insurance & Real Estate"),
("Financial Services"),
("Fishing"),
("Food"),
("Food & Beverage"),
("Food Processing & Sales"),
("Food Products Manufacturing"),
("Food Stores"),
("For-profit Education"),
("For-profit Prisons"),
("Foreign & Defense Policy"),
("Forestry"),
("Foundations, Philanthropists & Non-Profits"),
("Funeral Services"),
("Gambling & Casinos"),
("Garbage Collection/Waste Management"),
("Gas & Oil"),
("General Contractors"),
("Government Employee Unions"),
("Government Employees"),
("Green"),
("Gun Control"),
("Gun Rights"),
("Health"),
("Health Professionals"),
("Health Services/HMOs"),
("Hedge Funds"),
("HMOs & Health Care Services"),
("Home Builders"),
("Hospitals & Nursing Homes"),
("Hotels, Motels & Tourism"),
("Human Rights"),
("Ideological/Single-Issue"),
("Indian Gaming"),
("Industrial Robot"),
("Industrial Unions"),
("Information"),
("Information Technology"),
("Infrastructure"),
("Insurance"),
("Internet"),
("Israel Policy"),
("Labor"),
("Lawyers & Lobbyists"),
("Lawyers / Law Firms"),
("Leadership PACs"),
("Leisure"),
("LGBTQIA Rights & Issues"),
("Liberal/Democratic"),
("Liquor, Wine & Beer"),
("Livestock"),
("Lobbyists"),
("Lodging / Tourism"),
("Logging, Timber & Paper Mills"),
("Manufacturing, Misc"),
("Marijuana"),
("Marine Transport"),
("Meat processing & products"),
("Media"),
("Medical Supplies"),
("Mining"),
("Misc Business"),
("Misc Finance"),
("Misc Manufacturing & Distributing"),
("Misc Unions"),
("Miscellaneous Defense"),
("Miscellaneous Services"),
("Mortgage Bankers & Brokers"),
("Motion Picture Production & Distribution"),
("Music Production"),
("Natural Gas Pipelines"),
("News Media"),
("Newspaper, Magazine & Book Publishing"),
("Non-profits, Foundations & Philanthropists"),
("Nurses"),
("Nursing Homes/Hospitals"),
("Nutritional & Dietary Supplements"),
("Oil & Gas"),
("Other"),
("Payday Lenders"),
("Pharmaceutical Manufacturing"),
("Pharmaceuticals / Health Products"),
("Phone Companies"),
("Physicians & Other Health Professionals"),
("Postal Unions"),
("Poultry & Eggs"),
("Power Utilities"),
("Printing & Publishing"),
("Private Equity & Investment Firms"),
("Pro-Israel"),
("Professional Sports, Sports Arenas & Related Equipment & Services"),
("Progressive/Democratic"),
("Public Employees"),
("Public Sector Unions"),
("Publishing & Printing"),
("Radio/TV Stations"),
("Railroads"),
("Real Estate"),
("Record Companies/Singers"),
("Recorded Music & Music Production"),
("Recreation / Live Entertainment"),
("Religious Organizations/Clergy"),
("Republican Candidate Committees"),
("Republican Leadership PACs"),
("Republican/Conservative"),
("Residential Construction"),
("Restaurants & Drinking Establishments"),
("Retail Sales"),
("Retired"),
("Savings & Loans"),
("Schools/Education"),
("Scientific"),
("Sea Transport"),
("Securities & Investment"),
("Software"),
("Special Trade Contractors"),
("Sports, Professional"),
("Steel Production"),
("Stock Brokers/Investment Industry"),
("Student Loan Companies"),
("Sugar Cane & Sugar Beets"),
("Teachers Unions"),
("Teachers/Education"),
("Telecom Services & Equipment"),
("Telephone Utilities"),
("Textiles"),
("Timber, Logging & Paper Mills"),
("Tobacco"),
("Transportation"),
("Transportation Unions"),
("Trash Collection/Waste Management"),
("Trucking"),
("TV / Movies / Music"),
("TV Production"),
("Unions"),
("Unions, Airline"),
("Unions, Building Trades"),
("Unions, Industrial"),
("Unions, Misc"),
("Unions, Public Sector"),
("Unions, Teacher"),
("Unions, Transportation"),
("Universities, Colleges & Schools"),
("Vegetables & Fruits"),
("Venture Capital"),
("Waste Management"),
("Water"),
("Wholesale"),
("Wine, Beer & Liquor"),
("Women's Issues"),
("Wood");
